name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true # In job level will tell all combinations to continue the flow also if something failed 
    strategy:
      matrix: #I will basically will run 2 * 3 = 6 times (node-version * operating-system)
        node-version: [12, 14, 16] # we can define node versions that all of them will be testsed on the steps below 
        operating-system: [ubuntu-latest, windows-latest] # Here we defind different operations systems
        include: #This is a reserve key (Addinital combination that will addded to the matrix)
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: # This specific combination will not invoke in the matrix
          - node-version: 12
            operating-system: windows-latest
    runs-on: $ {{ matrix.operating-system }} #Those jobs will run in parallel  for the system within the array
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version:  {{ matrix.node-version }} #Here it the same with the node version
      - name: Install Dependecies
        run: npm ci
      - name: Build project
        run: npm run buid